### PR TITLE
Add a Fxuv function using mors tracks

### PR DESCRIPTION
**Pull request by EmmaPostolec**
In addition to the stellar files I added for the last pull request, I created a Fxuv_mors function. This function takes the stellar mass, the stellar rotation rate and the distance to the host star as arguments. It uses mors.Star() to load the evolution track of the star and return 2 arrays : the age of the star and the corresponding XUV flux. I wrote a small python script (test_fxuv_mors.py) to be sure it was working correctly.

### CODE REVIEW

**Review by lsoucasse — APPROVED** [review]
This new function returns a vector while other Fxuv functions return a scalar. But it makes sense given the significant time to generate the whole track.

Looks good!

**Comment by EmmaPostolec** [comment]
Thanks for pointing this out, @lsoucasse . Do you think I should change the output to a scalar like the other functions, or leave it like that? Let me know what you think is the better option.

**Comment by lsoucasse** [comment]
> Thanks for pointing this out, @lsoucasse . Do you think I should change the output to a scalar like the other functions, or leave it like that? Let me know what you think is the better option.

No I think it is OK as it is. Again, it is convenient to compute all the values, because of the cost of the track generation. Just something to keep in mind.

**Comment by EmmaPostolec** [comment]
Ok thanks for the advice @lsoucasse !

**Pull request merged**
