### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by lsoucasse**
This work reorganises the Zephyrus repository.

- All example scripts have been moved into the examples folder. Each example having its output plot and data if necessary.
- Data have been moved either in src package or in relevant example.
- The earth script has been turned into a test and checks for three different star age the XUV flux given by Mors and the escape value provided by EL_escape. Testing workflow has been added.

### CODE REVIEW

**Comment by lsoucasse** [comment]
Reminder: The `Fxuv_Johnstone` function in `src/zephyrus/XUV_flux.py` needs missing data.

**Comment by lsoucasse** [comment]
There is a reproducibility issue of the XUV flux provided by Mors accros different platform, see FormingWorlds/MORS#22. Once solved, would be good to add the extra data point catching this bug.

**Comment by lsoucasse** [comment]
> There is a reproducibility issue of the XUV flux provided by Mors accros different platform, see [FormingWorlds/MORS#22](https://github.com/FormingWorlds/MORS/issues/22). Once solved, would be good to add the extra data point catching this bug.

Done!

**Review by EmmaPostolec — APPROVED** [review]
Well done :)

**Pull request merged**
